# Generated by Django 5.1.7 on 2025-03-20 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='artist - name [album]')),
                ('updated_title', models.TextField(blank=True, help_text='artist - name [album]', null=True)),
                ('lyrics_id', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_lyrics', models.TextField(blank=True, null=True)),
                ('lyrics_db', models.IntegerField(default=0, help_text='0: custom, 1: spotify, 2: lrclibrary, 3: textyl')),
                ('delay', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
