# Generated by Django 5.1.7 on 2025-03-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(help_text='artist - name [album]', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='updated_title',
            field=models.CharField(blank=True, help_text='artist - name [album]', max_length=50, null=True),
        ),
    ]
