# Generated by Django 5.1.7 on 2025-03-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_song_title_alter_song_updated_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics_db',
            field=models.IntegerField(blank=True, help_text='0: custom, 1: spotify, 2: lrclibrary, 3: textyl', null=True),
        ),
    ]
